---
namespace: mighty_sponge
name: any_sync

version: %VERSION%
readme: README.md
authors:
  - Kirill Shklyaev <kirill@anytype.io>

description: Ansible roles for deploy any-sync-* daemons.

license_file: LICENSE.md

tags:
  - any_sync
  - any_sync_node
  - any_sync_consensusnode
  - any_sync_coordinator
  - any_sync_filenode

repository: https://github.com/anyproto/ansible-anysync
documentation: https://github.com/anyproto/ansible-anysync
issues: https://github.com/anyproto/ansible-anysync/issues
