---
- name: Copy config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ any_sync_coordinator_config_path }}/config.yml"
    mode: "0644"
  notify: Restart service

- name: Copy network config file
  ansible.builtin.template:
    src: network.yml.j2
    dest: "{{ any_sync_coordinator_config_path }}/network.yml"
    mode: "0644"

- name: Copy systemd init file
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/any-sync-coordinator.service
    mode: "0644"
  notify: Restart service

- name: Apply network configuration
  run_once: true
  ansible.builtin.shell: |
    sleep 10
    any-sync-confapply -c {{ any_sync_coordinator_config_path }}/config.yml -n {{ any_sync_coordinator_config_path }}/network.yml -e
