---

- name: Copy config file
  template:
    src: config.yml.j2
    dest: "{{ any_sync_coordinator_config_path }}/config.yml"
  notify: Restart any-sync-coordinator

- name: Copy network config file
  template:
    src: network.yml.j2
    dest: "{{ any_sync_coordinator_config_path }}/network.yml"

- name: Copy systemd init file
  template:
    src: service.j2
    dest: /etc/systemd/system/any-sync-coordinator.service
  notify: Restart any-sync-coordinator

- name: Apply network configuration
  run_once: true
  shell: |
    sleep 10
    any-sync-confapply -c {{ any_sync_coordinator_config_path }}/config.yml -n {{ any_sync_coordinator_config_path }}/network.yml -e
