---

- name: Install
  ansible.builtin.import_tasks: install.yml
  tags:
    - install

- name: Configure
  ansible.builtin.import_tasks: config.yml
  tags:
    - configure

- name: Service
  ansible.builtin.import_tasks: service.yml
  tags:
    - service
